### ISSUE TITLE
Is there a published web version of this?

### ISSUE THREAD

**Issue by winf-hsos** [evorto/karel#1]
Hi, thanks for sharing this code. I wonder if you have a published version of this somewhere to look at and use it with students?

Thanks,
Nicolas

**Comment by lukasnehrke** [comment]
I do not recommend using this software, as it is still under development and lacks a lot of important features.

You should stick with the original [Karel](https://github.com/fredoverflow/karel) by University of Hamburg.

**Comment by winf-hsos** [comment]
Ok, thanks. Yes, I am using the original already. We had some trouble with getting Java running on all > 90 laptops, so I thought maybe there is a web version.

Thanks!
